version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: rar_telegram_bot
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:rar_telegram_bot"
      - "traefik.frontend.entryPoints=http"
    env_file:
      - .env
